name: Build and test RAG pipeline

on:
    push:
        branches:
            - main
        tags:
            - '[0-9].[0-9].[0-9]'
    pull_request:
        types:
            - opened
        branches:
            - main

concurrency:
    group: ${{ github.ref}}
    cancel-in-progress: true

jobs:
    build-and-test:
        runs-on: ubuntu-24.04
        steps:
            - name: Build
              run: echo 'hello'
            - name: Test
              run: echo 'hi'
