name: Build and test RAG pipeline

on:
    push:
        branches:
            - main
        tags:
            - '[0-9].[0-9].[0-9]'
    pull_request:
        types:
            - opened
        branches:
            - main

concurrency:
    group: ${{ github.ref}}
    cancel-in-progress: true

jobs:
    build-and-test:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
            - name: Build and test
              env:
                OLLAMA_LLM_MODEL: llama3.2
              run: docker compose run -e OLLAMA_LLM_MODEL=${{ env.OLLAMA_LLM_MODEL }} rag && docker compose down
