name: Build and test RAG pipeline

on:
    push:
        branches:
            - main
        tags:
            - '[0-9].[0-9].[0-9]'
    pull_request:
        types:
            - opened
        branches:
            - main

concurrency:
    group: ${{ github.ref }}
    cancel-in-progress: true

jobs:
    build-and-test:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
            - name: Setup Docker buildx
              uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v.3.10.0
            - name: Build and cache Docker image
              uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1 # v6.16.0
              with:
                load: true
                cache-from: type=gha
                cache-to: type=gha,mode=max

            - name: Build and test
              env:
                OLLAMA_LLM_MODEL: llama3.2
              run: docker compose run -e OLLAMA_LLM_MODEL=${{ env.OLLAMA_LLM_MODEL }} rag && docker compose down
